### ISSUE TITLE
Side-by-side tweaks

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#33]
Hi @mthomas-ketchbrook , here are a few minor things that could be improved in the side-by-side map:

## 1. Default comparison

Set "period" as the default with the 1st and last years selected as left/right and `SCENARIOS[[1]]` as the constant 

## 2. Use names of scenarios

When comparing scenarios, the names of the scenarios are used, which is correct:

<img width="369" alt="Screenshot 2023-05-30 at 9 30 10 PM" src="https://github.com/PredictiveEcology/wbi_shiny/assets/831636/4d665333-2189-4c06-9528-5d13ea0515f8">

However, when period is selected and scenario becomes the constant, only the input value is passed and not the name:

<img width="390" alt="Screenshot 2023-05-30 at 9 29 48 PM" src="https://github.com/PredictiveEcology/wbi_shiny/assets/831636/5d1e45d3-b6ff-417d-b6ea-add0eac28581">

This can be looked up from the `SCENARIOS` data object, but is complicated by the conditional rendering.

Please update from main, I made a few small changes. Thanks.

**Comment by mthomas-ketchbrook** [comment]
Hi @psolymos, I pushed a few commits (directly to the `main` branch) that address these changes:

- def71b0c2a59f1b5aa50188b68cb5a8e2c2dd7ec makes "Period" the default comparison with the first and last years selected as left/right and `SCENARIOS[[1]]` as the constant
- 3165de6ff8e2d82911463200a5056f0ec38f37a8 grabs the *name* of the selected `SCENARIOS` list element (instead of the *value*) for display when "Scenario" is the constant

Feel free to try out the changes (available in the `main` branch) and close this issue if these changes resolve your requests.  Thanks!

**Comment by psolymos** [comment]
Fantastic. Thanks @mthomas-ketchbrook for the prompt response.
